github: ['safalamsall'] # Replace with up to 4 GitHub Sponsors-enabled usernames
patreon: 'safalamsall' # Replace with a single Patreon username
open_collective: 'safalamsall' # Replace with a single Open Collective username
ko_fi: 'safalamsall' # Replace with a single Ko-fi username
tidelift: 'npm/babel' # Replace with a single Tidelift platform-name/package-name
community_bridge: 'cloud-foundry' # Replace with a single Community Bridge project-name
liberapay: 'safalamsall' # Replace with a single Liberapay username
issuehunt: 'safalamsall' # Replace with a single IssueHunt username
lfx_crowdfunding: 'cloud-foundry' # Replace with a single LFX Crowdfunding project-name
polar: 'safalamsall' # Replace with a single Polar username
buy_me_a_coffee: 'safalamsall' # Replace with a single Buy Me a Coffee username
thanks_dev: 'safalamsall' # Replace with a single thanks.dev username
custom: ['link1', 'link2', 'link3', 'link4'] # Replace with up to 4 custom sponsorship URLs
